version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - localnet

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./api/.env
    depends_on:
      - mongodb
    networks:
      - localnet

volumes:
  mongodb_data:

networks:
  localnet:
    driver: bridge
