version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - localnet

volumes:
  mongodb_data:

networks:
  localnet:
    driver: bridge
